services:
  postgres:
    image: postgres:16
    container_name: incidentflow_postgres
    restart: always
    environment:
      POSTGRES_USER: incidentflow_user
      POSTGRES_PASSWORD: incidentflow_password
      POSTGRES_DB: incidentflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: