"""add departments relationships

Revision ID: 5ea1129e0fe0
Revises: a09e25a5c45e
Create Date: 2026-05-18 13:10:50.112486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea1129e0fe0'
down_revision: Union[str, Sequence[str], None] = 'a09e25a5c45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'departments', ['department_id'], ['id'])
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'department_id')
    # ### end Alembic commands ###
