"""add archived at to categories

Revision ID: 5f91feff1d31
Revises: bf4db8346813
Create Date: 2026-07-10 15:43:42.514689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f91feff1d31'
down_revision: Union[str, Sequence[str], None] = 'bf4db8346813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.alter_column('categories', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('categories', 'archived_at')
    # ### end Alembic commands ###
