"""add archive support to assignment groups

Revision ID: 70dbaec93300
Revises: 5bbd3a1efcc4
Create Date: 2026-07-14 14:07:00.871410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dbaec93300'
down_revision: Union[str, Sequence[str], None] = '5bbd3a1efcc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_groups', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.alter_column('assignment_groups', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment_groups', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('assignment_groups', 'archived_at')
    # ### end Alembic commands ###
