"""add sla lifecycle timestamps

Revision ID: b0cacd4f511c
Revises: f88a537e2fc6
Create Date: 2026-08-25 12:38:58.172486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0cacd4f511c'
down_revision: Union[str, Sequence[str], None] = 'f88a537e2fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sla_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('sla_breached_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tickets_sla_breached_at'), 'tickets', ['sla_breached_at'], unique=False)
    op.create_index(op.f('ix_tickets_sla_completed_at'), 'tickets', ['sla_completed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_sla_completed_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_sla_breached_at'), table_name='tickets')
    op.drop_column('tickets', 'sla_breached_at')
    op.drop_column('tickets', 'sla_completed_at')
    # ### end Alembic commands ###
