"""add sla due date to tickets

Revision ID: b304440109ae
Revises: 5ea1129e0fe0
Create Date: 2026-05-18 14:53:29.276247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b304440109ae'
down_revision: Union[str, Sequence[str], None] = '5ea1129e0fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sla_due_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'sla_due_at')
    # ### end Alembic commands ###
