"""add assignment group members

Revision ID: dca40b3e95fe
Revises: b0cacd4f511c
Create Date: 2026-08-25 15:40:18.420222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca40b3e95fe'
down_revision: Union[str, Sequence[str], None] = 'b0cacd4f511c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_group_id'], ['assignment_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_group_id', 'user_id', name='uq_assignment_group_member')
    )
    op.create_index(op.f('ix_assignment_group_members_assignment_group_id'), 'assignment_group_members', ['assignment_group_id'], unique=False)
    op.create_index(op.f('ix_assignment_group_members_id'), 'assignment_group_members', ['id'], unique=False)
    op.create_index(op.f('ix_assignment_group_members_user_id'), 'assignment_group_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_group_members_user_id'), table_name='assignment_group_members')
    op.drop_index(op.f('ix_assignment_group_members_id'), table_name='assignment_group_members')
    op.drop_index(op.f('ix_assignment_group_members_assignment_group_id'), table_name='assignment_group_members')
    op.drop_table('assignment_group_members')
    # ### end Alembic commands ###
